name: Scott Schermer
favicon: null
layout_spectrum: 0.50118
typography_spectrum: 0
title: Scott Schermer Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f6'
    - '#39434c'
    - '#c98431'
    - '#e2c4a0'
    - '#798086'
  brandStrength: 0.25735550723038614
  lightness: 0.13874984835274518
  saturation: 0.3125
  rhythmicContrast: 0.21035552327521145
purpose: []
