name: Scott Schermer
favicon: null
layout_spectrum: 0.7262327871285379
typography_spectrum: 0.11942523112520576
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.25735550723038614
  lightness: 0.13874984835274518
  saturation: 0.7003005596343428
  rhythmicContrast: 0.21035552327521145
purpose: []
